services:
  - type: web
    name: oraculo-api
    env: python
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    ports:
      - 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /docs
    plan: standard
    disks:
      - name: oraculo-data
        path: /app/db_oraculo

  - type: worker
    name: oraculo-ingestao-worker
    env: python
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: "python app/ingestao.py"
    autoDeploy: false
    disks:
      - name: oraculo-data
        path: /app/db_oraculo
    envVars:
      - key: OPENAI_API_KEY
        sync: false
